# Config File for shortcuter
#
# Lines which start with #, are comments!
#
# Add KeyValuePairs here not for command shortcuts
# The left is the shortcut and the right is the long command
# which will be executed!
#
# All Arguments after the the shortcut command will be added
# to the runned command!

hi=echo Hallo World
hi2=echo $PATH
hi3=cd ..

# Clean ZIG
zigclean=rmdir /s /q %LOCALAPPDATA%\zig

# Add a Custom Start Message
--overwrite-start-message=true
--start-message-file=sx-message.txt
--start-message-color=Cyan

# Enable Local Commands
# Option to enable local Command SX files in the current dir which will
# then be loaded
--enable-local-commands=true
# To decide if the Local or Global Commands should be used
# Default it false
--override-global-commands=false

# Change the Default used Shell on Windows to bash
#--windows-default-shell=cmd

# Use Bash although on Linux
--linux-default-shell=bash

# Add Info after the Start Message
--add-info-to-start-message=true

# Number Guess Game
--numberguess-lol=halooo

# For the UI
--windows-sx-ui-button1="C:\Users\schueler\AppData\Local\Applauncher\applauncher.exe"
--windows-sx-ui-button2=hi
--windows-sx-ui-button3=hi
--windows-sx-ui-button4=hi
--windows-sx-ui-button5=hi
--windows-sx-ui-button6=hi
--windows-sx-ui-button7=hi
--windows-sx-ui-button8=hi
--windows-sx-ui-button9=hi
--windows-sx-ui-button10=hi
--windows-sx-ui-button11=hi
--windows-sx-ui-button12=hi
--windows-sx-ui-button13=hi
--windows-sx-ui-button14=hi
--windows-sx-ui-button15=hi
--windows-sx-ui-button16=hi

# UI Callbacks
--windows-sx-ui-button1-name=echo Applaunscher
--windows-sx-ui-button2-name=echo Hallo World
--windows-sx-ui-button3-name=echo Hallo World
--windows-sx-ui-button4-name=echo Hallo World
--windows-sx-ui-button5-name=echo Hallo World
--windows-sx-ui-button6-name=echo Hallo World
--windows-sx-ui-button7-name=echo Hallo World
--windows-sx-ui-button8-name=echo Hallo World
--windows-sx-ui-button9-name=echo Hallo World
--windows-sx-ui-button10-name=echo Hallo World
--windows-sx-ui-button11-name=echo Hallo World
--windows-sx-ui-button12-name=echo Hallo World
--windows-sx-ui-button13-name=echo Hallo World
--windows-sx-ui-button14-name=echo Hallo World
--windows-sx-ui-button15-name=echo Hallo World
--windows-sx-ui-button16-name=echo Hallo World

# UI Terminal Open
--windows-sx-ui-button1-window=echo false

# Batch Folder Tool
# --windows-foldertool-batch-f4=echo Test

random=echo This is a lot more random

# Update Finder
finderupdate=go install github.com/shadowdara/finder/cmd/finder@latest
