# Config File for shortcuter
#
# Lines which start with #, are comments!
#
# Add KeyValuePairs here not for command shortcuts
# The left is the shortcut and the right is the long command
# which will be executed!
#
# All Arguments after the the shortcut command will be added
# to the runned command!

hi=echo Hallo World

--overwrite-start-message=true
--start-message-file=sx-message.txt

